version: '3'
services:
    my-service:
        build: .
        depends_on:
            - postgres
        ports:
            - 3000:3000
        # Add your service configuration here

    postgres:
        image: postgres
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        # Add any additional PostgreSQL configuration here